version: '3.8'
services:
  sqlserver:
    container_name: cosmolab-sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "CosmoLab@2024"
      MSSQL_PID: Developer
    ports:
      - "1433:1433"
    volumes:
      - mssql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/1433"]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 20s
    networks:
      - cosmolab-net
  rabbitmq:
    container_name: cosmolab-rabbitmq
    image: rabbitmq:3.12-management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      # - ./rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins:ro,Z
      - rabbitmq-data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
      - "15692:15692"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - cosmolab-net
volumes:
  mssql-data:
  rabbitmq-data:
networks:
  cosmolab-net:
    external: true
